name: UIElementInspector
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    macOS: "15.0"
  defaultConfig: Debug
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    PRODUCT_BUNDLE_IDENTIFIER: com.example.UIElementInspector

targets:
  UIElementInspector:
    type: application
    platform: macOS
    sources:
      - path: UIElementInspector
        excludes:
          - "*.xcassets"
    resources:
      - path: UIElementInspector/Resources
    settings:
      base:
        INFOPLIST_FILE: UIElementInspector/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: UIElementInspector/Resources/UIElementInspector.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 7YNKVG32P3
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        COMBINE_HIDPI_IMAGES: YES
    info:
      path: UIElementInspector/Resources/Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleDisplayName: UI Element Inspector
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        NSHumanReadableCopyright: "Copyright © 2026. All rights reserved."
        NSAccessibilityUsageDescription: "UI要素を検査するためにアクセシビリティ権限が必要です。"
        LSApplicationCategoryType: public.app-category.developer-tools
